// <auto-generated />
namespace ShopAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _987654 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_987654));
        
        string IMigrationMetadata.Id
        {
            get { return "201710300252208_987654"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
